server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: weather-service

app:
  jwt:
    secret: ${JWT_SECRET:default-secret-key-change-in-production-must-be-at-least-256-bits-long!!}
    access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION:3600000}
    refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRATION:604800000}
  weather:
    api-key: ${WEATHER_API_KEY:}
    base-url: https://api.openweathermap.org

springdoc:
  api-docs:
    path: /weather/v3/api-docs
  swagger-ui:
    path: /weather/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
