apiVersion: v1
kind: Secret
metadata:
  name: iot-secrets
  namespace: iot-backend
type: Opaque
stringData:
  db-username: iot_user
  db-password: iot_pass
  jwt-secret: default-secret-key-change-in-production-must-be-at-least-256-bits-long!!
  weather-api-key: ""
